apiVersion: v1
kind: ConfigMap
metadata:
  name: xrpld-config
  namespace: xrpl
  labels:
    app: xrpld

data:
  rippled.cfg: |
    [server]
    port_rpc_admin_local
    port_ws_public

    [port_rpc_admin_local]
    port = 5005
    ip = 127.0.0.1
    admin = 127.0.0.1
    protocol = http

    [port_ws_public]
    port = 80
    ip = 0.0.0.0
    protocol = ws

    [node_db]
    type=NuDB
    path=/var/lib/rippled/db/nudb

    [ledger_history]
    256

    [ips_fixed]

    [validators]

    [rpc_startup]
    {{ "command": "ledger_accept" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrpld
  namespace: xrpl
  labels:
    app: xrpld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrpld
  template:
    metadata:
      labels:
        app: xrpld
    spec:
      containers:
        - name: xrpld
          image: xrpllabsofficial/xrpld:latest
          ports:
            - containerPort: 80
            - containerPort: 5005
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rippled
      volumes:
        - name: config-volume
          configMap:
            name: xrpld-config
---
apiVersion: v1
kind: Service
metadata:
  name: xrpld-service
  namespace: xrpl
  labels:
    app: xrpld
spec:
  selector:
    app: xrpld
  ports:
    - name: ws-public
      port: 80
      targetPort: 80
    - name: rpc-admin
      port: 5005
      targetPort: 5005
  type: ClusterIP
