//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod images;
pub mod permissions;
pub mod profile_has_user;
pub mod profiles;
pub mod role_has_permission;
pub mod roles;
pub mod user_has_role;
pub mod users;
