//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use serde::{Deserialize, Serialize};
use thiserror::Error;
use validator::Validate;

pub mod prelude;

pub mod network_has_node;
pub mod networks;
pub mod node_ports;
pub mod nodes;
pub mod permissions;
pub mod profile_has_user;
pub mod profiles;
pub mod role_has_permission;
pub mod roles;
pub mod user_has_role;
pub mod users;

/// The logic for validating the model and converting the validation errors to a `sea_orm::DbErr` is taken from the loco crate.
/// <https://github.com/loco-rs/loco/blob/master/src/validation.rs>

#[derive(Debug, Error)]
#[error("Failed to validate model: {0}")]
pub struct ModelValidationErrors(validator::ValidationErrors);

impl From<ModelValidationErrors> for sea_orm::DbErr {
    fn from(e: ModelValidationErrors) -> sea_orm::DbErr {
        into_db_error(&e)
    }
}

pub(crate) trait Validatable {
    fn validate(&self) -> Result<(), ModelValidationErrors> {
        Ok(self.validator().validate().map_err(ModelValidationErrors)?)
    }

    fn validator(&self) -> Box<dyn Validate>;
}

#[derive(Debug, Deserialize, Serialize)]
pub struct ModelValidationMessage {
    pub code: String,
    pub message: Option<String>,
}

#[must_use]
pub fn into_db_error(errors: &ModelValidationErrors) -> sea_orm::DbErr {
    use std::collections::BTreeMap;

    let errors = &errors.0;
    let error_data: BTreeMap<String, Vec<ModelValidationMessage>> = errors
        .field_errors()
        .iter()
        .map(|(field, field_errors)| {
            let errors = field_errors
                .iter()
                .map(|err| ModelValidationMessage {
                    code: err.code.to_string(),
                    message: err.message.as_ref().map(std::string::ToString::to_string),
                })
                .collect();
            ((*field).to_string(), errors)
        })
        .collect();
    let json_errors = serde_json::to_value(error_data);
    match json_errors {
        Ok(errors_json) => sea_orm::DbErr::Custom(errors_json.to_string()),
        Err(err) => sea_orm::DbErr::Custom(format!(
            "[before_save] could not parse validation errors. err: {err}"
        )),
    }
}
