//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "networks")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    pub subnet: String,
    pub driver: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::network_has_node::Entity")]
    NetworkHasNode,
}

impl Related<super::network_has_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NetworkHasNode.def()
    }
}

impl Related<super::nodes::Entity> for Entity {
    fn to() -> RelationDef {
        super::network_has_node::Relation::Nodes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::network_has_node::Relation::Networks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
