//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_has_permission::Entity")]
    RoleHasPermission,
}

impl Related<super::role_has_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleHasPermission.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_has_permission::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::role_has_permission::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
