//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use async_trait::async_trait;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use validator::Validate;

use crate::Validatable;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::profile_has_user::Entity")]
    ProfileHasUser,
}

impl Related<super::profile_has_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileHasUser.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::profile_has_user::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::profile_has_user::Relation::Profiles.def().rev())
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, _insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        self.validate()?;
        Ok(self)
    }
}

/// Validator for the Profile entity.
#[derive(Debug, Validate, Deserialize)]
pub struct Validator {
    #[validate(length(min = 2, max = 100))]
    pub name: String,
}

impl Validatable for ActiveModel {
    fn validator(&self) -> Box<dyn Validate> {
        Box::new(Validator {
            name: self.name.as_ref().to_owned(),
        })
    }
}
