//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::profile_has_user::Entity")]
    ProfileHasUser,
}

impl Related<super::profile_has_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileHasUser.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::profile_has_user::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::profile_has_user::Relation::Profiles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
