//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_has_permission::Entity")]
    RoleHasPermission,
    #[sea_orm(has_many = "super::user_has_role::Entity")]
    UserHasRole,
}

impl Related<super::role_has_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleHasPermission.def()
    }
}

impl Related<super::user_has_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHasRole.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_has_permission::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::role_has_permission::Relation::Roles.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_has_role::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_has_role::Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
