apiVersion: v1
kind: Namespace
metadata:
  name: xrpl

---
apiVersion: v1
kind: Service
metadata:
  name: validator
  namespace: xrpl
spec:
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: rpc
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: peer
  selector:
    app: validator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  namespace: xrpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
        - name: validator
          image: xrpllabsofficial/xrpld
          ports:
            - containerPort: 5005
            - containerPort: 6006
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/xrpld
      volumes:
        - name: config-volume
          configMap:
            name: xrpld-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xrpld-config
  namespace: xrpl
data:
  rippled.cfg: |
    [server]
    port_rpc_admin_local
    port_peer
    [port_rpc_admin_local]
    port = 5005
    ip = 0.0.0.0
    admin = 127.0.0.1
    protocol = http
    [port_peer]
    port = 6006
    ip = 0.0.0.0
    protocol = peer
    [node_size]
    medium
    [database_path]
    /var/lib/rippled/db
    [debug_logfile]
    /var/log/rippled/debug.log
    [sntp_servers]
    time.windows.com
    time.apple.com
    time.nist.gov
    pool.ntp.org
    [validators_file]
    validators.txt
    [network_quorum]
    1
    [validator_token]
    YOUR_VALIDATOR_TOKEN
    [ips]
    127.0.0.1 6006
