[package]
name = "k3d"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
validator = { version = "0.20.0", features = ["derive"] }
