version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - DIST_PATH=dist/bl_frontend/browser
    volumes:
      - ../..:/workspaces:cached
    networks:
      - blocklocal

networks:
  blocklocal:
