version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - DIST_PATH=dist/bl_frontend/browser
    volumes:
      - ../..:/workspaces:cached
      - /workspaces/BlockLocal/bl_frontend/dist/bl_frontend/browser
      - frontend:/workspaces/BlockLocal/bl_frontend/dist/bl_frontend/browser:rw
    networks:
      - blocklocal
      - blocklocal-dev

  frontend:
    image: nginx:alpine
    container_name: frontend
    command: sleep infinity
    depends_on:
      - backend
    volumes:
      - frontend:/html/blocklocal:ro
    networks:
      - blocklocal

  backend:
    image: rancher/k3d:5.3
    privileged: true
    container_name: backend
    depends_on:
      - dev
    command: sleep infinity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6443:6443"
      - "8080:80"
      - "8443:443"
    networks:
      - blocklocal
    environment:
      K3D_KUBECONFIG_MODE: "666" 
      K3D_CLUSTER_NAME: "bl-default"
      K3D_REGISTRY_HTTP_PORT: "5000"
      K3D_REGISTRY_HTTP_HOST: ""
      K3D_REGISTRY_HTTP_ENABLE: "true"

volumes:
  frontend:
  backend:

networks:
  blocklocal:
    driver: bridge
  blocklocal-dev:
    driver: bridge

