services:
  xrpld:
    image: xrpllabsofficial/xrpld:latest
    ports:
      - "5005:5005"
      - "6006:6006"
    environment:
      - XRPLD_RPC_PORT=5005
      - XRPLD_WS_PORT=6006
      - XRPLD_VALIDATORS=validators.txt
    volumes:
      - ../config/validators.txt:/validators.txt
    networks:
      - xrpld
    restart: always